# Generated by Django 6.0.3 on 2026-04-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
