# Generated by Django 6.0.3 on 2026-05-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attribute_name_en_attribute_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='unit',
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AttributeUnit',
        ),
    ]
