# Generated by Django 6.0.3 on 2026-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attribute_name_en_attribute_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_moderator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='draft', max_length=20),
        ),
    ]
