# Generated by Django 6.0.3 on 2026-05-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_description_moderator_product_status'),
        ('product', '0008_remove_attribute_unit_alter_unit_unit_and_more'),
    ]

    operations = [
    ]
