# Generated by Django 6.0.3 on 2026-05-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description_moderator'),
        ('product', '0009_merge_20260504_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='company.company'),
        ),
    ]
