# Generated by Django 6.0.3 on 2026-05-16 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_cartitem_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_session_product',
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('session_key', 'product'), name='unique_session_product'),
        ),
    ]
