# Generated by Django 6.0.3 on 2026-05-16 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description_moderator'),
        ('product', '0011_remove_favourite_unique_session_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_moderator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='attribute',
            name='color',
            field=models.FileField(blank=True, null=True, upload_to='products/attributes/colors/'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='product.variant'),
        ),
        migrations.CreateModel(
            name='ProductConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('sku', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='product_constructors/files/')),
                ('product_type', models.CharField(choices=[('ready', 'Ready'), ('made_to_order', 'Made to order'), ('both', 'Both')], default='ready', max_length=20)),
                ('price_type', models.CharField(choices=[('exact', 'Exact'), ('range', 'Range'), ('on_request', 'On request')], default='on_request', max_length=20)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=55)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=55)),
                ('is_active', models.BooleanField(default=True)),
                ('moq', models.PositiveIntegerField()),
                ('lead_time_min', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('lead_time_max', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewing', 'Reviewing'), ('returned_for_correction', 'Returned for correction'), ('accepted', 'Accepted')], default='draft', max_length=30)),
                ('moderator_comment', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product_constructors', to='product.category')),
                ('moq_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moq_unit_product_constructors', to='product.unit')),
                ('original_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_constructor', to='product.product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_product_constructors', to='company.company')),
            ],
            options={
                'verbose_name': 'Product Constructor',
                'verbose_name_plural': 'Product Constructors',
            },
        ),
        migrations.CreateModel(
            name='VariantConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('description_ru', models.TextField(blank=True, default='', null=True)),
                ('description_uz', models.TextField(blank=True, default='', null=True)),
                ('sku_variant', models.CharField(blank=True, max_length=150)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moq_override', models.PositiveIntegerField(blank=True, default=0)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('original_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_constructors', to='product.variant')),
                ('product_constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_constructors', to='product.productconstructor')),
            ],
            options={
                'verbose_name': 'Variant Constructor',
                'verbose_name_plural': 'Variant Constructors',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('variant_constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_constructors', to='product.variantconstructor')),
            ],
            options={
                'verbose_name': 'Characteristic Constructor',
                'verbose_name_plural': 'Characteristic Constructors',
            },
        ),
        migrations.CreateModel(
            name='VariantMediaConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to='product_constructors/media/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_variant_media_constructors', to=settings.AUTH_USER_MODEL)),
                ('variant_constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_media_constructors', to='product.variantconstructor')),
            ],
            options={
                'verbose_name': 'Variant Media Constructor',
                'verbose_name_plural': 'Variant Media Constructors',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValueConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue')),
                ('variant_constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value_constructors', to='product.variantconstructor')),
            ],
            options={
                'verbose_name': 'Product Attribute Value Constructor',
                'verbose_name_plural': 'Product Attribute Value Constructors',
                'unique_together': {('variant_constructor', 'attribute', 'attribute_value')},
            },
        ),
    ]
