# Generated by Django 6.0.3 on 2026-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_description_moderator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='color',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/attribute_values/images/'),
        ),
    ]
