# Generated by Django 6.0.3 on 2026-05-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_attribute_color_attributevalue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
