# Generated by Django 6.0.3 on 2026-05-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_attributevalue_value_en_attributevalue_value_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAttributeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('attribute_values', models.ManyToManyField(related_name='variant_attribute_stocks', to='product.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_stocks', to='product.variant')),
            ],
            options={
                'verbose_name': 'Variant Attribute Stock',
                'verbose_name_plural': 'Variant Attribute Stocks',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='attribute_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='product.variantattributestock'),
        ),
        migrations.CreateModel(
            name='VariantAttributeStockConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('attribute_values', models.ManyToManyField(related_name='variant_attribute_stock_constructors', to='product.attributevalue')),
                ('variant_constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_stock_constructors', to='product.variantconstructor')),
            ],
            options={
                'verbose_name': 'Variant Attribute Stock Constructor',
                'verbose_name_plural': 'Variant Attribute Stock Constructors',
            },
        ),
    ]
