# Generated by Django 6.0.3 on 2026-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_variantattributestock_cartitem_attribute_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconstructor',
            name='status',
            field=models.CharField(choices=[('moderation', 'Moderation'), ('reviewing', 'Reviewing'), ('returned_for_correction', 'Returned for correction'), ('accepted', 'Accepted')], default='moderation', max_length=30),
        ),
    ]
