# Generated by Django 6.0.3 on 2026-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productconstructor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
