# Generated by Django 6.0.3 on 2026-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_cartitem_attributes_cartitem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
