# Generated by Django 6.0.3 on 2026-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
