# Generated by Django 6.0.3 on 2026-08-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_company_avg_answer_time_and_more'),
        ('product', '0021_unit_unit_en_unit_unit_ru_unit_unit_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='company.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_products', to='company.company'),
        ),
        migrations.AlterField(
            model_name='productconstructor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_product_constructors', to='company.company'),
        ),
    ]
