# Generated by Django 6.0.3 on 2026-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
