# Generated by Django 6.0.3 on 2026-05-05 09:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faq_description_en_faq_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.FileField(upload_to='aboutus/media/')),
            ],
            options={
                'verbose_name': 'About Us Images',
                'verbose_name_plural': 'About Us Images',
            },
        ),
        migrations.AddField(
            model_name='aboutus',
            name='information_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='information_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='information_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
