# Generated by Django 6.0.3 on 2026-04-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='draft', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.FileField(blank=True, null=True, upload_to='companies/logos/')),
                ('cover', models.FileField(blank=True, null=True, upload_to='companies/covers/')),
                ('avg_answer_time', models.CharField(blank=True, max_length=100)),
                ('avg_delivery_time', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('longitude', models.FloatField(default=69.2385)),
                ('latitude', models.FloatField(default=41.2982)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('permission', models.CharField(choices=[('manage_sales', 'Manage sales'), ('manage_members', 'Manage members'), ('manage_products', 'Manage products'), ('manage_company_info', 'Manage company info')], max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='company.companymember')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='companies', to='company.industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='company.region'),
        ),
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='companies/certificates/')),
                ('earned_at', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='company.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'earned_at'], name='company_com_company_8ea2ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.FileField(upload_to='companies/gallery/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='company.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='company_com_company_e1197a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_company_member_user_company'),
        ),
        migrations.AddConstraint(
            model_name='companymemberpermission',
            constraint=models.UniqueConstraint(fields=('member', 'permission'), name='unique_company_member_permission'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['region', 'status'], name='company_com_region__6a0b11_idx'),
        ),
    ]
