# Generated by Django 6.0.3 on 2026-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='own_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
