# Generated by Django 6.0.3 on 2026-04-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_facebook_company_instagram_company_own_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
