# Generated by Django 6.0.3 on 2026-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companygallery_title_en_companygallery_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description_moderator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
