# Generated by Django 6.0.3 on 2026-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_description_moderator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companymemberpermission',
            name='unique_company_member_permission',
        ),
        migrations.AddField(
            model_name='companymember',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='description_moderator',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='CompanyMemberPermission',
        ),
    ]
