# Generated by Django 6.0.3 on 2026-06-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_order_and_more'),
        ('company', '0007_remove_companymemberpermission_unique_company_member_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('responded_at', models.DateTimeField()),
                ('response_time_seconds', models.PositiveIntegerField()),
                ('buyer_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_entry', to='chat.message')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_time_entries', to='company.company')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_time_entries', to='chat.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='company_res_company_71308a_idx'), models.Index(fields=['conversation', 'buyer_message'], name='company_res_convers_ce5300_idx')],
            },
        ),
    ]
