# Generated by Django 6.0.3 on 2026-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_responsetimeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
