# Generated by Django 6.0.3 on 2026-06-16 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='INN must be 9 digets')]),
        ),
    ]