# Generated by Django 6.0.3 on 2026-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='avg_answer_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='avg_delivery_time',
        ),
        migrations.AddField(
            model_name='company',
            name='max_answer_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='max_delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='min_answer_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='min_delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
