# Generated by Django 6.0.3 on 2026-06-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
