# Generated by Django 6.0.3 on 2026-06-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_redirect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
