# Generated by Django 6.0.3 on 2026-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_category_remove_order_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('ready', 'Ready'), ('rfq', 'RFQ'), ('both', 'Both')], default='ready', max_length=10),
        ),
    ]
