# Generated by Django 6.0.3 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_budget_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('negotiation', 'Negotiation'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
                default='negotiation',
                max_length=20,
            ),
        ),
    ]
