# Generated by Django 6.0.3 on 2026-05-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
        ('product', '0015_variantattributestock_cartitem_attribute_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='attribute_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.variantattributestock'),
        ),
    ]
