# Generated by Django 6.0.3 on 2026-05-21 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_attribute_stock'),
        ('product', '0015_variantattributestock_cartitem_attribute_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQOrderItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='order.orderitem')),
                ('value_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.attributevalue')),
            ],
            options={
                'verbose_name': 'RFQ Order Item Attribute',
                'verbose_name_plural': 'RFQ Order Item Attributes',
            },
        ),
        migrations.DeleteModel(
            name='RFQOrderAttribute',
        ),
    ]
