# Generated by Django 6.0.3 on 2026-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rfq_order_item_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
