# Generated by Django 6.0.3 on 2026-08-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_company_avg_answer_time_and_more'),
        ('order', '0009_order_discount_order_discount_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_orders', to='company.company'),
        ),
    ]
