# Generated by Django 6.0.3 on 2026-05-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='buyer'),
        ),
    ]
