# Generated by Django 6.0.3 on 2026-06-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('UZS', "Uzbek So'm"), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('CNY', 'Chinese Yuan')], default='UZS', max_length=3),
        ),
    ]
