# Generated by Django 6.0.3 on 2026-06-03 18:32

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
