# Generated by Django 6.0.3 on 2026-05-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('order', '0001_initial'),
        ('product', '0009_merge_20260504_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='order.order'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='product.variant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
